services:
  database:
    image: "postgres:16.0-alpine3.18"
    env_file:
      - ../../.env
    ports:
      - "5432:5432"
  admin:
    image: "dpage/pgadmin4"
    env_file:
      - ../../.env
    ports:
      - "8080:80"
